config/routes.rb
Rails.application.routes.draw do
  resources :pets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  #validations

  #i want my pet to always have a name
  validates :name, presence: true

  #the species should be included in a given list
  validates :species, inclusion: {in: %w(dog cat rabbit turtle pidgeon)}

  def self.species
     %w(dog cat rabbit turtle pidgeon)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.found_on = Date.today
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end




  private

  def pet_params
    params.require(:pet).permit(:name,:species,:address)

  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets725</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(pet) do |f| %>
<%= f.input :name %>
<%= f.input :species, collection: Pet.species %>
<%= f.input :address %>
<%= f.button :submit %>
<% end %>

app/views/pets/edit.html.erb
<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<h1>Pets</h1>
<ul>
  <% @pets.each do |pet| %>
  <li>
   <i class="fas fa-dragon"></i> Name: <%= link_to pet.name, pet_path(pet) %> - Address: <%= pet.address %> - Species: <%= pet.species %> - Found_on: <%= pet.found_on %>
  </li>
  <% end %>
</ul>

<%= link_to "New Pet", new_pet_path %>

app/views/pets/new.html.erb
<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<h1>Pet Profile</h1>
  <p> Name: <%= @pet.name %> </p>
  <p> Address: <%= @pet.address %></p>
  <p> Species: <%= @pet.species %> </p>
  <p> Found_on: <%= @pet.found_on %></p>

<%= link_to "edit", edit_pet_path(@pet) %>
<%= link_to "Delete", pet_path(@pet), method: :delete, data: {confirm: "Are you sure?"} %>